### ISSUE TITLE
Composer installation does not support Magneto 2.4

### ISSUE THREAD

**Issue by swnsma** [ViaBill-Integrations/ViaBill-Magento-2#2]
If you are trying to install the extension on Magneto 2.4.* project via composer, it shows an error the module can not be installed due to compatibility conflicts.
<img width="1075" alt="Screenshot 2021-02-17 at 17 13 04" src="https://user-images.githubusercontent.com/9420807/108224530-ac284580-7143-11eb-8d97-cf3c33584cbe.png">
Current, 4.0.0 version does not support Magneto Framework version 103.0.0 which is required for Magento 2.4.
However, Packagist contains message that 2.4 should be supported.
<img width="1207" alt="Screenshot 2021-02-17 at 17 13 16" src="https://user-images.githubusercontent.com/9420807/108224629-c7935080-7143-11eb-9d49-1614c6c710cf.png">

Could you resolve the issue with incompatibility?

**Comment by ViaBill-Integrations** [comment]
Hi there,

 Thank you for reaching out to the ViaBill onboarding team.

 We've received your message, and we'll be in touch within 2 business days.

 Kind regards,

 The Onboarding Team

 

 

 
   Previous-message-reference:
<ViaBill-Integrations/ViaBill-Magento-2/issues/2@github.com>

 Previous-message-reference:
<69a0ddb1ec4c4a95a4e707ca19d5c9b9@email.dixa.io>

**Comment by Josniii** [comment]
Hi @swnsma 
I'm the developer @ WEXO who has been responsible for the 4.0 version update. I just pushed a few commits which were in the Marketplace release for this module but hadn't been pushed to Github - could you try installing dev-master via composer instead of requiring the 4.0.0 release, and letting me know if the issue persists?

Regards,
Jonas Søndergaard @ WEXO.

**Comment by swnsma** [comment]
Hi @Josniii,

With **dev-master** everything works fine.
However, it's not an option if composer settings is set to 'minimum stability - stable'.
Could you advice when new version from current master branch could be expected?
Thank's in advance!

**Comment by Josniii** [comment]
Hi @swnsma 
I've tagged the newest changes as 4.0.1, which should be composer compatible with Magento 2.4. Please try it out!

**Comment by swnsma** [comment]
Hi @Josniii,
It works! Thank you!
