### ISSUE TITLE
Pricetag design in cart

### ISSUE THREAD

**Issue by kasperth** [ViaBill-Integrations/ViaBill-Magento-2#3]
### Preconditions
Clean Magento 2.4.3-p1
ViaBill module installed
### Steps to reproduce (*)
1. In the admin panel, Go to Stores > Configuration > Sales > Payment Methods > ViaBill > PriceTag Settings > Enable on Cart Summary. Set it to Yes.
2. Clear the cache
3. Go to storefront
4. Add Product to cart and go to cart page
5. Check the responsiveness of price tag block design.
### Expected result (*)
Price tag design in cart summary should look proper in all the devices.

### Actual result (*)
Price tag design in cart summary does not look proper in smaller screens. The design breaks with a discount block.
![pricetag_design_issue](https://user-images.githubusercontent.com/5848718/154641039-6b06c17f-5251-4b36-a62b-6cab91d833c6.png)

### Recommended solution
File path:  viabillhq/module-payment/view/frontend/web/template/viabillPriceTag.html
Line number: 10

Here, the module checks if the page type is “basket” or not. If it is a cart page (“basket” type), then it adds “Float: Right” property inline. Due to this when the frontend theme is blank or any theme inheriting it, The Price tag block breaks summary design. Here “text-align: right;” can also be applied in order to fix this.

- [ ] Severity: S0 - Affects critical data or functionality and leaves users without workaround.
- [ ]  Severity: S1 - Affects critical data or functionality and forces users to employ a workaround.
- [X]  Severity: S2 - Affects non-critical data or functionality and forces users to employ a workaround.
- [ ]  Severity: S3 - Affects non-critical data or functionality and does not force users to employ a workaround.
- [ ]  Severity: S4 - Affects aesthetics, professional look and feel, “quality” or “usability”.

**Comment by ViaBill-Integrations** [comment]
Hi there,

Thank you for reaching out to the ViaBill onboarding team.

We've received your message, and we'll be in touch within 2 business days.

Kind regards,

 The Onboarding Team





Previous-message-reference: 
***@***.***>

Previous-message-reference: ***@***.***>

**Comment by kasperth** [comment]
@ViaBill-Integrations this issue have ben resolved in the version 1.0.16.
